image: openjdk:jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- build
- docker

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
    - main-partition/build/libs/*.jar
    expire_in: 1 week

docker-image-master:
  image: docker:latest
  stage: docker
  dependencies:
  - build
  services:
  - docker:dind
  script:
  - cd main-partition
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/lievendoclo/project-kali-server .
  - docker push $CI_REGISTRY/lievendoclo/project-kali-server:latest
  only:
  - master

docker-image-tags:
  image: docker:latest
  stage: docker
  dependencies:
  - build
  services:
  - docker:dind
  script:
  - cd main-partition
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/lievendoclo/project-kali-server:$CI_COMMIT_REF_NAME .
  - docker push $CI_REGISTRY/lievendoclo/project-kali-server:$CI_COMMIT_REF_NAME
  only:
  - tags

docker-image:
  manual: true
  image: docker:latest
  stage: docker
  dependencies:
  - build
  services:
  - docker:dind
  script:
  - cd main-partition
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/lievendoclo/project-kali-server:$CI_COMMIT_REF_NAME .
  - docker push $CI_REGISTRY/lievendoclo/project-kali-server:$CI_COMMIT_REF_NAME
  except:
  - tags
  - master
