image: openjdk:jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
#- qa
- build
- release-image

#test:
#  stage: qa
#  script: ./gradlew --build-cache check
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
    - main-partition/build/libs/*.jar

release-image:
  image: docker:latest
  stage: release-image
  dependencies:
  - build
  services:
  - docker:dind
  script:
  - cd main-partition
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/lievendoclo/project-kali-server .
  - docker push $CI_REGISTRY/lievendoclo/project-kali-server:latest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull

