image: openjdk:jdk-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- static-analysis
- qa
- build
- release-image

ktlint:
  stage: static-analysis
  script: ./gradlew ktlintCheck

detekt:
  stage: static-analysis
  script: ./gradlew detektCheck

test:
  stage: qa
  script: ./gradlew --build-cache check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull

release-image:
  image: docker:latest
  stage: release-image
  script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  - ./gradlew --build-cache buildDocker
  - docker push "sourcedbvba/project-kali-server:latest"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull

