image: openjdk:jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- qa
- build
- release-image

test:
  stage: qa
  script: ./gradlew --build-cache check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull

release-image:
  image: docker:latest
  stage: release-image
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - ./gradlew --build-cache buildDockerCiLatest
  - docker push "registry.gitlab.com/lievendoclo/project-kali-server:latest"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull

